package dev.kobol.stdlib

/**
 * kobol.sort — Sorting utilities callable from Kobol programs.
 *
 * The Kobol pipeline's SORT BY stage generates calls into this module so that
 * custom sort keys work without reflection in the generated bytecode.
 */
object KobolSort {

    // ── Generic list sort ─────────────────────────────────────────────────

    /** Return a new list sorted by [keyFn] ascending (stable). */
    @JvmStatic fun <T, K : Comparable<K>> sortBy(list: List<T>, keyFn: (T) -> K): List<T> =
        list.sortedBy(keyFn)

    /** Return a new list sorted by [keyFn] descending (stable). */
    @JvmStatic fun <T, K : Comparable<K>> sortByDescending(list: List<T>, keyFn: (T) -> K): List<T> =
        list.sortedByDescending(keyFn)

    /** Return a new list in natural (ascending) order — elements must be Comparable. */
    @JvmStatic fun <T : Comparable<T>> sort(list: List<T>): List<T> = list.sorted()

    /** Return a new list in natural descending order — elements must be Comparable. */
    @JvmStatic fun <T : Comparable<T>> sortDescending(list: List<T>): List<T> =
        list.sortedDescending()

    /** Stable sort with an explicit [comparator]. */
    @JvmStatic fun <T> sortWith(list: List<T>, comparator: Comparator<T>): List<T> =
        list.sortedWith(comparator)

    // ── Convenience: String lists ─────────────────────────────────────────

    @JvmStatic fun sortStrings(list: List<String>, ignoreCase: Boolean = false): List<String> =
        if (ignoreCase) list.sortedWith(String.CASE_INSENSITIVE_ORDER) else list.sorted()

    // ── Partition / Group ─────────────────────────────────────────────────

    /** Split [list] into (matches, nonMatches) based on [predicate]. */
    @JvmStatic fun <T> partition(list: List<T>, predicate: (T) -> Boolean): Pair<List<T>, List<T>> =
        list.partition(predicate)

    /** Group [list] elements into a Map keyed by [keyFn]. */
    @JvmStatic fun <T, K> groupBy(list: List<T>, keyFn: (T) -> K): Map<K, List<T>> =
        list.groupBy(keyFn)
}
