package dev.kobol.codegen

import dev.kobol.parser.ast.*
import dev.kobol.semantic.KobolType
import dev.kobol.semantic.Symbol
import dev.kobol.semantic.TypeChecker

/**
 * Kobol AST → Java source code transpiler.
 *
 * Maps Kobol constructs to idiomatic Java:
 *   RECORD       → public static final class (POJO)
 *   DATA section → private static fields on the main class
 *   PROCEDURE    → private static method
 *   COMPUTE/LET  → Java assignment
 *   DISPLAY      → System.out.println(...)  with StringBuilder for interpolation
 *   STOP RUN     → System.exit(0)
 *   FOR EACH     → for (var x : list)
 *   WHILE        → while (cond)
 *   IF/ELSE      → if/else
 *   TRY/ON       → try/catch/finally
 *   CALL         → direct Java method invocation
 *
 * Ergonomics:
 *   String interpolation "{name}" → StringBuilder chain  (ER-4)
 *   Script mode (no PROGRAM header) → wraps in Main class  (ER-6)
 *   DISPLAY TABLE/LABEL/FORMAT     → KobolDisplay helpers  (ER-9)
 */
class JavaTranspiler(
    private val checker: TypeChecker,
    private val moduleRegistry: dev.kobol.semantic.ModuleRegistry = dev.kobol.semantic.ModuleRegistry(),
) {

    private val sb    = StringBuilder()
    private var indent = 0
    private val namedConditions = mutableMapOf<String, Expression>()
    private var currentClass = "Main"  // tracks the outer class name for method references

    /**
     * Transpile [program] to Java source.
     *
     * [className] is the name of the emitted top-level class. It defaults to a name
     * derived from `program.name`, but callers should pass the SAME name they use
     * for the output file (and the bytecode path), since Java requires a public
     * class to live in a file of the same name — otherwise `javac` rejects it.
     */
    fun transpile(program: Program, className: String = javaClass(program.name)): String {
        sb.clear(); indent = 0
        namedConditions.clear()
        for (cond in program.namedConditions) namedConditions[cond.name] = cond.expr

        line("// Generated by kobolc — do not edit")
        line("// Source program: ${program.name}")
        blank()
        line("import dev.kobol.runtime.*;")
        line("import java.math.BigDecimal;")
        line("import java.math.RoundingMode;")
        line("import java.util.*;")
        line("import java.time.*;")
        blank()

        line("public final class $className {")
        currentClass = className
        indent++

        // RECORD declarations → inner static classes
        for (rec in program.records) emitRecord(rec)

        // DATA section → static fields
        program.dataSection?.items?.forEach { emitDataField(it) }

        blank()

        // PROCEDURE declarations → static methods
        val exportedNames: Set<String> = program.moduleDecl?.exports?.map { it.name }?.toSet() ?: emptySet()
        for (proc in program.procedures) emitProcedure(proc, proc.exported || proc.name in exportedNames)

        // main() entry point — delegate to MAIN procedure
        val mainProc = program.procedures.find { it.name == "MAIN" }
        blank()
        line("public static void main(String[] args) {")
        indent++
        line("dev.kobol.runtime.KobolEnv.setArgs(args);")   // §27.1 ACCEPT FROM ARGUMENT
        if (mainProc != null) line("${javaIdent(mainProc.name)}();")
        else                  line("// No MAIN procedure found")
        indent--
        line("}")

        indent--
        line("}")
        return sb.toString()
    }

    // -------------------------------------------------------------------------
    // Records
    // -------------------------------------------------------------------------

    private fun emitRecord(rec: RecordDecl) {
        blank()
        line("public static final class ${javaClass(rec.name)} {")
        indent++
        for (f in rec.fields) {
            val jt = kobolTypeToJava(checker.toKobolType(f.type))
            line("public $jt ${javaIdent(f.name)} = ${defaultValue(checker.toKobolType(f.type))};")
        }
        // Simple toString for DISPLAY
        val fields = rec.fields.joinToString(" + \", \" + ") { "\"${f(it.name)}=\" + ${javaIdent(it.name)}" }
        blank()
        line("@Override public String toString() { return \"${rec.name}{\" + $fields + \"}\"; }")
        indent--
        line("}")
    }

    // -------------------------------------------------------------------------
    // Data fields
    // -------------------------------------------------------------------------

    private fun emitDataField(item: DataItem) {
        val kType = if (item.type != null) checker.toKobolType(item.type)
                    else item.initializer?.let { inferLiteralType(it) } ?: KobolType.UnknownType
        val jType = kobolTypeToJava(kType)
        val init  = if (item.initializer != null) " = ${emitExprFor(kType, item.initializer)}"
                    else " = ${defaultValue(kType)}"
        line("private static $jType ${javaIdent(item.name)}$init;")
    }

    // -------------------------------------------------------------------------
    // Procedures
    // -------------------------------------------------------------------------

    private fun emitProcedure(proc: ProcedureDecl, exported: Boolean = false) {
        blank()
        val retType = if (proc.isAsync) {
            val inner = if (proc.returnType != null) kobolTypeToJava(checker.toKobolType(proc.returnType)) else "Void"
            "java.util.concurrent.CompletableFuture<$inner>"
        } else if (proc.returnType != null) kobolTypeToJava(checker.toKobolType(proc.returnType))
        else "void"
        val params  = proc.params.joinToString(", ") {
            "${kobolTypeToJava(checker.toKobolType(it.type))} ${javaIdent(it.name)}"
        }
        val visibility = if (exported) "public" else "private"
        if (proc.isAsync) {
            line("$visibility static $retType ${javaIdent(proc.name)}($params) {")
            indent++
            line("return java.util.concurrent.CompletableFuture.supplyAsync(() -> {")
            indent++
            for (stmt in proc.body) emitStatement(stmt)
            if (proc.returnType == null) line("return null;")
            indent--
            line("}, dev.kobol.runtime.KobolConcurrent.INSTANCE);")
            indent--
            line("}")
        } else {
            line("$visibility static $retType ${javaIdent(proc.name)}($params) {")
            indent++
            for (stmt in proc.body) emitStatement(stmt)
            indent--
            line("}")
        }
    }

    // -------------------------------------------------------------------------
    // Statements
    // -------------------------------------------------------------------------

    private fun emitStatement(stmt: Statement) {
        when (stmt) {
            is MoveStatement     -> line("${emitRef(stmt.to)} = ${emitExprFor(refType(stmt.to), stmt.from)};")
            is AcceptStatement   -> emitAccept(stmt)
            is ComputeStatement  -> line("${emitRef(stmt.target)} = ${emitExprFor(refType(stmt.target), stmt.expr)};")
            is MapPutStatement   -> line("${emitRef(stmt.map)}.put(${emitExpr(stmt.key)}, ${emitExpr(stmt.value)});")
            is MapGetStatement   -> {
                // Cast to the boxed value type; assignment to a primitive target auto-unboxes (#12).
                val vt = (refType(stmt.map) as? KobolType.MapType)?.valueType ?: refType(stmt.into)
                val boxed = when (vt) {
                    is KobolType.IntegerType  -> "Long"
                    is KobolType.SmallIntType -> "Integer"
                    is KobolType.BooleanType  -> "Boolean"
                    else                      -> kobolTypeToJava(vt)
                }
                line("${emitRef(stmt.into)} = ($boxed) ${emitRef(stmt.map)}.get(${emitExpr(stmt.key)});")
            }
            is LocalVarDecl      -> {
                val kType = stmt.type?.let { checker.toKobolType(it) }
                            ?: inferLiteralType(stmt.initializer)
                line("${kobolTypeToJava(kType)} ${javaIdent(stmt.name)} = ${emitExprFor(kType, stmt.initializer)};")
            }
            is AddStatement      -> emitArith(stmt.target, "+", stmt.operand, stmt.giving)
            is SubtractStatement -> emitArith(stmt.from, "-", stmt.operand, stmt.giving)
            is MultiplyStatement -> emitArith(stmt.right, "*", stmt.left, stmt.giving)
            is DivideStatement   -> emitArith(stmt.into, "/", stmt.divisor, stmt.giving, stmt.dividingMode)
            is DisplayStatement  -> emitDisplay(stmt)
            is PerformStatement  -> {
                if (stmt.moduleAlias != null) {
                    val mod = moduleRegistry.resolveByAlias(stmt.moduleAlias)
                        ?: error("Unknown module alias '${stmt.moduleAlias}' at transpile time")
                    val proc = mod.procedures[stmt.procedureName.uppercase()]
                    val args = emitProcArgs(stmt.args, proc?.params)
                    line("${mod.jvmClassName}.${javaIdent(stmt.procedureName)}($args);")
                } else {
                    val sym  = checker.symbols.resolve(stmt.procedureName) as? Symbol.ProcedureSymbol
                    val args = emitProcArgs(stmt.args, sym?.params)
                    line("${javaIdent(stmt.procedureName)}($args);")
                }
            }
            is CallStatement     -> {
                val method = stmt.method.split(".").joinToString(".")
                val args   = stmt.args.joinToString(", ") { emitExpr(it) }
                val call   = "$method($args)"
                if (stmt.giving != null) line("${emitRef(stmt.giving)} = $call;")
                else line("$call;")
            }
            is IfStatement       -> emitIf(stmt)
            is WhileStatement    -> {
                line("while (${emitExpr(stmt.condition)}) {")
                indent++; stmt.body.forEach { emitStatement(it) }; indent--
                line("}")
            }
            is ForEachStatement  -> {
                val iterType = checker.typeOf(stmt.iterable)
                val elemJava = when (iterType) {
                    is KobolType.ListType -> kobolTypeToJava(iterType.elementType)
                    else                  -> "var"
                }
                line("for ($elemJava ${javaIdent(stmt.variable)} : ${emitExpr(stmt.iterable)}) {")
                indent++; stmt.body.forEach { emitStatement(it) }; indent--
                line("}")
            }
            is RepeatStatement   -> {
                line("for (long __repeat = 0, __limit = (long)(${emitExpr(stmt.count)}); __repeat < __limit; __repeat++) {")
                indent++; stmt.body.forEach { emitStatement(it) }; indent--
                line("}")
            }
            is OpenStatement     -> line("/* OPEN ${stmt.fileName} FOR ${stmt.mode} */")
            is ReadStatement     -> line("/* READ ${stmt.fileName} */")
            is WriteStatement    -> line("/* WRITE ${stmt.fileName} */")
            is CloseStatement    -> line("/* CLOSE ${stmt.fileName} */")
            is WriteJsonStatement -> {
                val method = if (stmt.pretty) "writePrettyToFile" else "writeToFile"
                line("dev.kobol.stdlib.KobolJson.$method(${emitExpr(stmt.value)}, ${emitExpr(stmt.filepath)});")
            }
            is WriteXmlStatement -> {
                if (stmt.rootName != null) {
                    line("dev.kobol.stdlib.KobolXml.writeWithRoot(${emitExpr(stmt.value)}, ${emitExpr(stmt.filepath)}, ${emitExpr(stmt.rootName)}, ${stmt.pretty});")
                } else {
                    val method = if (stmt.pretty) "writePrettyToFile" else "writeToFile"
                    line("dev.kobol.stdlib.KobolXml.$method(${emitExpr(stmt.value)}, ${emitExpr(stmt.filepath)});")
                }
            }
            is ParseJsonStatement -> {
                if (stmt.asList) {
                    val method = if (stmt.fromFile) "parseFileArray" else "parseJsonArray"
                    line("${emitRef(stmt.into)} = dev.kobol.stdlib.KobolJson.$method(${emitExpr(stmt.source)});")
                } else {
                    val method = if (stmt.fromFile) "parseFileInto" else "parseInto"
                    line("dev.kobol.stdlib.KobolJson.$method(${emitRef(stmt.into)}, ${emitExpr(stmt.source)});")
                }
            }
            is ParseXmlStatement -> {
                if (stmt.asList) {
                    val method = if (stmt.fromFile) "parseFileElements" else "parseXmlElements"
                    line("${emitRef(stmt.into)} = dev.kobol.stdlib.KobolXml.$method(${emitExpr(stmt.source)});")
                } else if (stmt.namespaces.isNotEmpty()) {
                    // §30.3 — validate the root namespace against the declared URIs.
                    val uris   = stmt.namespaces.joinToString(", ") { emitExpr(it.second) }
                    val method = if (stmt.fromFile) "parseFileIntoNamespaces" else "parseIntoNamespaces"
                    line("dev.kobol.stdlib.KobolXml.$method(${emitRef(stmt.into)}, ${emitExpr(stmt.source)}, new String[]{$uris});")
                } else {
                    val method = if (stmt.fromFile) "parseFileInto" else "parseInto"
                    line("dev.kobol.stdlib.KobolXml.$method(${emitRef(stmt.into)}, ${emitExpr(stmt.source)});")
                }
            }
            is WithPrecisionStatement -> {
                if (stmt.roundingMode != null) {
                    line("dev.kobol.stdlib.KobolMathContext.pushWithRounding(\"${stmt.precisionName}\", \"${stmt.roundingMode}\");")
                } else {
                    line("dev.kobol.stdlib.KobolMathContext.push(\"${stmt.precisionName}\");")
                }
                line("try {")
                indent++; stmt.body.forEach { emitStatement(it) }; indent--
                line("} finally {")
                line("    dev.kobol.stdlib.KobolMathContext.pop();")
                line("}")
            }
            is RoundStatement -> {
                val scale = emitExpr(stmt.scale)
                val target = emitRef(stmt.target)
                if (stmt.mode != null) {
                    line("$target = dev.kobol.stdlib.KobolMath.roundWithMode($target, $scale, \"${stmt.mode}\");")
                } else {
                    line("$target = dev.kobol.stdlib.KobolMath.round($target, $scale);")
                }
            }
            is TryStatement      -> emitTry(stmt)
            is RaiseStatement    -> {
                val msg = stmt.message?.let { emitExpr(it) } ?: "\"${stmt.exceptionType}\""
                line("throw new KobolException($msg);")
            }
            is ReturnStatement   -> {
                if (stmt.value != null) line("return ${emitExpr(stmt.value)};")
                else line("return;")
            }
            is StopRunStatement  -> {
                val code = stmt.exitCode?.let { emitExpr(it) } ?: "0"
                line("System.exit((int)($code));")
            }
            // Logging and concurrency statements — stub out for Java transpiler
            is LogStatement             -> line("/* LOG ${stmt.level} */")
            is ConcurrentBlock          -> line("/* CONCURRENT block (${stmt.branches.size} branches) */")
            is ParallelForEachStatement -> line("/* PARALLEL FOR EACH ${stmt.variable} */")
            is ValidateStatement        -> line("/* VALIDATE */")
            is MatchStatement           -> line("/* MATCH */")
            is SleepStatement -> {
                val factor = when (stmt.unit) {
                    SleepUnit.MILLISECONDS -> 1L
                    SleepUnit.SECONDS      -> 1000L
                    SleepUnit.MINUTES      -> 60_000L
                }
                val millis = if (factor == 1L) emitExpr(stmt.amount) else "(${emitExpr(stmt.amount)} * ${factor}L)"
                line("try { Thread.sleep($millis); } catch (InterruptedException __e) { Thread.currentThread().interrupt(); }")
            }
            is AssertStatement -> {
                val cond = emitExpr(stmt.condition)
                if (stmt.message != null) {
                    line("dev.kobol.runtime.KobolTest.assertTrue($cond, ${emitExpr(stmt.message)});")
                } else {
                    line("dev.kobol.runtime.KobolTest.assertTrue($cond);")
                }
            }
            is AssertRaisesStatement -> {
                // Catch class via the SHARED resolver; '/'+'$' → '.' for Java source form.
                val exClass = kobolExceptionJvmName(stmt.exceptionType).replace('/', '.').replace('$', '.')
                line("{ // ASSERT RAISES ${stmt.exceptionType}  (own scope so __raised never clashes)")
                indent++
                line("boolean __raised = false;")
                line("try {")
                indent++; emitStatement(stmt.body); indent--
                line("} catch ($exClass __e) { __raised = true; }")
                line("dev.kobol.runtime.KobolTest.assertTrue(__raised, \"Expected ${stmt.exceptionType} to be raised\");")
                indent--
                line("}")
            }
            is MockStatement -> {
                line("dev.kobol.runtime.KobolMockRegistry.register(\"${stmt.procedureName}\", ${emitExpr(stmt.returns)});")
            }

            // ── Group 11: HTTP client ─────────────────────────────────────────
            is HttpCallStatement -> {
                val url      = emitExpr(stmt.url)
                val headers  = if (stmt.headers  != null) emitExpr(stmt.headers)  else "null"
                val timeout  = if (stmt.timeout  != null) emitExpr(stmt.timeout)  else "30L"
                val HTTP     = "dev.kobol.stdlib.KobolHttp"
                val call = when (stmt.httpMethod) {
                    "GET", "DELETE" -> "$HTTP.${stmt.httpMethod.lowercase()}($url, $headers, $timeout)"
                    else -> {
                        val body = if (stmt.body != null) emitExpr(stmt.body) else "null"
                        "$HTTP.${stmt.httpMethod.lowercase()}($url, $headers, $body, $timeout)"
                    }
                }
                if (stmt.giving != null) line("${emitRef(stmt.giving)} = $call;")
                else line("$call;")
            }

            // ── Group 11: JDBC bridge ─────────────────────────────────────────
            is JdbcConnectStatement -> {
                val url  = emitExpr(stmt.url)
                val user = if (stmt.user     != null) emitExpr(stmt.user)     else "null"
                val pw   = if (stmt.password != null) emitExpr(stmt.password) else "null"
                line("dev.kobol.stdlib.KobolJdbc.connect($url, $user, $pw);")
            }
            is JdbcQueryStatement -> {
                val sql    = emitExpr(stmt.sql)
                val params = "new Object[]{ ${stmt.params.joinToString { emitExpr(it) }} }"
                val call   = "dev.kobol.stdlib.KobolJdbc.query($sql, $params)"
                if (stmt.into != null) line("${emitRef(stmt.into)} = $call;")
                else line("$call;")
            }
            is JdbcExecuteStatement -> {
                val sql    = emitExpr(stmt.sql)
                val params = "new Object[]{ ${stmt.params.joinToString { emitExpr(it) }} }"
                line("dev.kobol.stdlib.KobolJdbc.execute($sql, $params);")
            }
            is JdbcDisconnectStatement -> line("dev.kobol.stdlib.KobolJdbc.disconnect();")

            // ── Group 12: REST server ─────────────────────────────────────────
            is ServerStatement -> {
                val SRV = "dev.kobol.stdlib.KobolServer"
                for (ep in stmt.endpoints) {
                    // Emit endpoint as a local lambda capturing nothing
                    val bodyCode = buildString {
                        for (s in ep.body) {
                            // Inline transpile statements into lambda — simplified
                            append("// endpoint body — see generated class\n")
                        }
                    }
                    // Generate a static helper method name and register
                    val safePath = ep.path.replace(Regex("[^A-Za-z0-9_]"), "_")
                    val helperName = "__endpoint_${ep.method}_$safePath"
                    line("$SRV.register(\"${ep.method}\", \"${ep.path}\", ${currentClass}::$helperName);")
                }
                line("$SRV.start((int)(${emitExpr(stmt.port)}));")
                // Emit helper methods
                for (ep in stmt.endpoints) {
                    val safePath = ep.path.replace(Regex("[^A-Za-z0-9_]"), "_")
                    val helperName = "__endpoint_${ep.method}_$safePath"
                    emitEndpointHelper(helperName, ep)
                }
            }
            is RespondStatement -> {
                val SRV  = "dev.kobol.stdlib.KobolServer"
                val JSON = "dev.kobol.stdlib.KobolJson"
                if (stmt.statusCode != null) {
                    line("$SRV.respondStatus((int)(${emitExpr(stmt.statusCode)}));")
                }
                val value = if (stmt.asJson) "$JSON.toJson(${emitExpr(stmt.value)})" else emitExpr(stmt.value)
                line("return $value;")
            }
            is AwaitStatement -> {
                line("${emitRef(stmt.into)} = (${kobolTypeToJava(checker.typeOf(stmt.into))}) ${emitRef(stmt.future)}.join();")
            }

            // ── Group 13: NoSQL document store ──────────────────────────────
            is NoSqlConnectStatement    -> line("dev.kobol.stdlib.KobolMongo.connect(${emitExpr(stmt.url)}, ${emitExpr(stmt.database)});")
            is NoSqlDisconnectStatement -> line("dev.kobol.stdlib.KobolMongo.disconnect();")
            is NoSqlFindStatement       -> {
                val filter = if (stmt.filter != null) emitMongoFilterJava(stmt.filter) else "null"
                val call = if (stmt.findOne)
                    "dev.kobol.stdlib.KobolMongo.findOne(${emitExpr(stmt.collection)}, $filter)"
                else
                    "dev.kobol.stdlib.KobolMongo.find(${emitExpr(stmt.collection)}, $filter)"
                line("${emitRef(stmt.giving)} = $call;")
            }
            is NoSqlSaveStatement       -> {
                if (stmt.upsert) {
                    line("dev.kobol.stdlib.KobolMongo.upsert(${emitExpr(stmt.collection)}, null, ${emitRef(stmt.document)});")
                } else {
                    line("dev.kobol.stdlib.KobolMongo.save(${emitExpr(stmt.collection)}, ${emitRef(stmt.document)});")
                }
            }
            is NoSqlDeleteStatement     -> line("dev.kobol.stdlib.KobolMongo.delete(${emitExpr(stmt.collection)}, ${emitMongoFilterJava(stmt.filter)});")
            is NoSqlCountStatement      -> {
                val filter = if (stmt.filter != null) emitMongoFilterJava(stmt.filter) else "null"
                line("${emitRef(stmt.giving)} = dev.kobol.stdlib.KobolMongo.count(${emitExpr(stmt.collection)}, $filter);")
            }

            // ── Group 14: Cache / key-value store ───────────────────────────
            is CacheConnectStatement    -> line("dev.kobol.stdlib.KobolRedis.connect(${emitExpr(stmt.url)});")
            is CacheDisconnectStatement -> line("dev.kobol.stdlib.KobolRedis.disconnect();")
            is CacheGetStatement        -> line("${emitRef(stmt.giving)} = dev.kobol.stdlib.KobolRedis.get(${emitExpr(stmt.key)});")
            is CacheSetStatement        -> {
                if (stmt.ttlSeconds != null) {
                    line("dev.kobol.stdlib.KobolRedis.setEx(${emitExpr(stmt.key)}, ${emitExpr(stmt.value)}, ${emitExpr(stmt.ttlSeconds)});")
                } else {
                    line("dev.kobol.stdlib.KobolRedis.set(${emitExpr(stmt.key)}, ${emitExpr(stmt.value)});")
                }
            }
            is CacheDeleteStatement     -> line("dev.kobol.stdlib.KobolRedis.delete(${emitExpr(stmt.key)});")
            is CacheExistsStatement     -> line("${emitRef(stmt.giving)} = dev.kobol.stdlib.KobolRedis.exists(${emitExpr(stmt.key)});")
        }
    }

    /** Emit a Java expression string representing a MongoDB Bson filter. */
    private fun emitMongoFilterJava(expr: Expression): String {
        val F = "com.mongodb.client.model.Filters"
        return when {
            expr is BinaryExpr && expr.op == BinaryOp.AND ->
                "$F.and($F.and(${emitMongoFilterJava(expr.left)}, ${emitMongoFilterJava(expr.right)}))"
            expr is BinaryExpr && expr.op == BinaryOp.OR ->
                "$F.or($F.or(${emitMongoFilterJava(expr.left)}, ${emitMongoFilterJava(expr.right)}))"
            expr is BinaryExpr && expr.op in MONGO_COMPARISON_OPS -> {
                val field = if (expr.left is Reference) (expr.left as Reference).parts.joinToString(".") else "value"
                val value = emitExpr(expr.right)
                val method = when (expr.op) {
                    BinaryOp.EQ  -> "eq"
                    BinaryOp.NEQ -> "ne"
                    BinaryOp.LT  -> "lt"
                    BinaryOp.GT  -> "gt"
                    BinaryOp.LEQ -> "lte"
                    BinaryOp.GEQ -> "gte"
                    else         -> "eq"
                }
                "$F.$method(\"$field\", $value)"
            }
            else -> "null"
        }
    }

    private fun emitEndpointHelper(name: String, ep: EndpointHandler) {
        val SRV = "dev.kobol.stdlib.KobolServer"
        blank()
        line("private static String $name(String body) {")
        indent++
        // Initialise path-parameter locals
        for (param in ep.pathParams) {
            line("String $param = $SRV.currentPathParam(\"$param\");")
        }
        for (s in ep.body) emitStatement(s)
        line("return \"\"; // fallthrough")
        indent--
        line("}")
    }

    private fun emitArith(target: Reference, op: String, operand: Expression, giving: Reference?, dividingMode: String? = null) {
        val lhs = emitRef(target)
        val rhs = emitExpr(operand)
        val dest = if (giving != null) emitRef(giving) else lhs
        // Resolve the full operand type (field chains included) so a record-field
        // money/decimal operand like `invoice.amount` takes the BigDecimal
        // arithmetic path, not `+`/`-`. `target` is the lhs operand here.
        val kType = refType(target)
        if (kType is KobolType.MoneyType || kType is KobolType.DecimalType) {
            val javOp = when (op) {
                "+" -> "add"; "-" -> "subtract"; "*" -> "multiply"; "/" -> "divide"
                else -> op
            }
            val mc = "dev.kobol.stdlib.KobolMathContext.current()"
            if (op == "/") {
                val roundArg = dividingMode ?: "HALF_EVEN"
                line("$dest = ($mc != null) ? $lhs.${javOp}($rhs, $mc) : $lhs.${javOp}($rhs, java.math.RoundingMode.$roundArg);")
            } else {
                line("$dest = ($mc != null) ? $lhs.${javOp}($rhs, $mc) : $lhs.${javOp}($rhs);")
            }
        } else {
            line("$dest = $lhs $op $rhs;")
        }
    }

    private fun emitDisplay(stmt: DisplayStatement) {
        // §27.2 DISPLAY PROGRESS renders in-place to stderr (void), not via println.
        val only = stmt.values.singleOrNull()
        if (only is BuiltinCall && only.name == "DISPLAY_PROGRESS") {
            line("dev.kobol.runtime.KobolDisplay.progress((long)(${emitExpr(only.args[0])}), (long)(${emitExpr(only.args[1])}), ${emitExpr(only.args[2])});")
            return
        }
        val arg = stmt.values.joinToString(" + \" \" + ") { emitDisplayArg(it) }
        line("System.out.println($arg);")
    }

    private fun emitDisplayArg(expr: Expression): String = when (expr) {
        is BuiltinCall -> when (expr.name) {
            "DISPLAY_TABLE"       -> "KobolDisplay.table(${emitExpr(expr.args[0])})"
            "DISPLAY_LABEL"       -> "KobolDisplay.label(${emitExpr(expr.args[0])}, ${emitExpr(expr.args[1])})"
            "DISPLAY_FORMAT"      -> "KobolDisplay.format(${emitExpr(expr.args[0])}, ${emitExpr(expr.args[1])})"
            "DISPLAY_JSON"        -> "dev.kobol.stdlib.KobolJson.toJson(${emitExpr(expr.args[0])})"
            "DISPLAY_JSON_PRETTY" -> "dev.kobol.stdlib.KobolJson.toPrettyJson(${emitExpr(expr.args[0])})"
            "DISPLAY_STYLED"      -> "dev.kobol.runtime.KobolDisplay.styled(${emitExpr(expr.args[0])}, ${emitExpr(expr.args[1])}, ${emitExpr(expr.args[2])}, ${emitExpr(expr.args[3])})"
            "DISPLAY_XML"         -> "dev.kobol.stdlib.KobolXml.toXml(${emitExpr(expr.args[0])})"
            "DISPLAY_XML_PRETTY"  -> "dev.kobol.stdlib.KobolXml.toPrettyXml(${emitExpr(expr.args[0])})"
            else                  -> emitExpr(expr)
        }
        else -> emitExpr(expr)
    }

    private fun emitIf(stmt: IfStatement) {
        line("if (${emitExpr(stmt.condition)}) {")
        indent++; stmt.thenBranch.forEach { emitStatement(it) }; indent--
        for (ei in stmt.elseIfClauses) {
            line("} else if (${emitExpr(ei.condition)}) {")
            indent++; ei.body.forEach { emitStatement(it) }; indent--
        }
        if (stmt.elseBranch != null) {
            line("} else {")
            indent++; stmt.elseBranch.forEach { emitStatement(it) }; indent--
        }
        line("}")
    }

    private fun emitTry(stmt: TryStatement) {
        line("try {")
        indent++; stmt.body.forEach { emitStatement(it) }; indent--
        for (h in stmt.handlers) {
            val binding = h.binding?.let { javaIdent(it) } ?: "__ex"
            line("} catch (Exception $binding) { // ON ${h.exceptionType}")
            indent++; h.body.forEach { emitStatement(it) }; indent--
        }
        if (stmt.ensure != null) {
            line("} finally {")
            indent++; stmt.ensure.forEach { emitStatement(it) }; indent--
        }
        line("}")
    }

    // -------------------------------------------------------------------------
    // Expression emitter
    // -------------------------------------------------------------------------

    private fun emitExpr(expr: Expression): String = when (expr) {
        is Literal -> when (expr.kind) {
            LiteralKind.INTEGER -> "${expr.value}L"
            LiteralKind.DECIMAL -> "new BigDecimal(\"${expr.value}\")"
            LiteralKind.STRING  -> "\"${escapeJavaString(expr.value.toString())}\""
            LiteralKind.BOOLEAN -> expr.value.toString()
        }

        is Reference -> emitRef(expr)

        is BinaryExpr -> emitBinary(expr)

        is UnaryExpr -> when (expr.op) {
            UnaryOp.NEGATE -> "(-${emitExpr(expr.operand)})"
            UnaryOp.NOT    -> "(!${emitExpr(expr.operand)})"
        }

        is StringTemplateExpr -> emitStringTemplate(expr)

        is BuiltinCall -> emitBuiltin(expr)

        is RecordLiteralExpr -> {
            val className = javaClass(expr.typeName)
            val args = expr.fields.joinToString(", ") { emitExpr(it.value) }
            // Use a builder pattern: create instance, then set fields
            val fieldSets = expr.fields.joinToString("; ") {
                "__rec_${javaIdent(expr.typeName)}.${javaIdent(it.name)} = ${emitExpr(it.value)}"
            }
            val varName = "__rec_${javaIdent(expr.typeName)}"
            // Inline block expression isn't valid Java — emit as a helper call
            // We'll use a lambda trick or just inline the assignments at statement level
            // For expression context, we need a different approach: allocate + init
            "new $className()"
        }

        is NamedArgument -> emitExpr(expr.value)

        is PipelineExpr  -> emitPipeline(expr)

        // F12 — dormant backend, best-effort only: emits `new <owner>(args)` but does NOT
        // resolve IMPORT aliases / stdlib paths to FQNs the way the ASM path does, so the alias
        // form won't compile as Java. Folded into F11 (port properly if the backend is revived).
        is NewExpr -> "new ${expr.owner}(${expr.args.joinToString(", ") { emitExpr(it) }})"

        // CALL in expression position (F14): emit the same `owner.method(args)` Java the CALL
        // statement emits — the dotted owner is a Java static class or an instance variable either way.
        is CallExpr -> "${expr.method}(${expr.args.joinToString(", ") { emitExpr(it) }})"

        // #v7 — list indexing. Dormant backend, best-effort: 1-based → 0-based List.get; the
        // element stays boxed (the ASM path unboxes/casts via castFromObject — ported if revived).
        is IndexExpr -> "${emitExpr(expr.target)}.get((int)(${emitExpr(expr.index)}) - 1)"
    }

    /**
     * Binary operators, type-aware.
     *
     * BigDecimal has no `==`/`+`/`-`/`*`/`/` operators in Java, and `==` on it is
     * reference equality (always wrong for value comparison). When either operand is
     * a DECIMAL/MONEY value we route to BigDecimal methods, mirroring [emitArith]:
     *   - comparisons → `compareTo(...)` (scale-insensitive: 1.50 == 1.5), and
     *   - arithmetic  → `add/subtract/multiply/divide`, honouring the active
     *     KobolMathContext so WITH PRECISION blocks apply.
     * Primitive operands keep the plain Java operators.
     */
    private fun emitBinary(expr: BinaryExpr): String {
        val decimal = (expr.op in DECIMAL_OPS) &&
            (isDecimalExpr(expr.left) || isDecimalExpr(expr.right) || expr.dividingMode != null)
        if (decimal) return emitDecimalBinary(expr)

        val l = emitExpr(expr.left)
        val r = emitExpr(expr.right)
        return when (expr.op) {
            BinaryOp.EQ       -> "($l == $r)"
            BinaryOp.NEQ      -> "($l != $r)"
            BinaryOp.LT       -> "($l < $r)"
            BinaryOp.GT       -> "($l > $r)"
            BinaryOp.LEQ      -> "($l <= $r)"
            BinaryOp.GEQ      -> "($l >= $r)"
            BinaryOp.AND      -> "($l && $r)"
            BinaryOp.OR       -> "($l || $r)"
            BinaryOp.ADD      -> "($l + $r)"
            BinaryOp.SUBTRACT -> "($l - $r)"
            BinaryOp.MULTIPLY -> "($l * $r)"
            BinaryOp.DIVIDE   -> "($l / $r)"
            BinaryOp.POWER    -> "(long)Math.pow((double)$l, (double)$r)"
        }
    }

    /** Emit a BigDecimal-typed binary op. Caller guarantees [expr.op] in [DECIMAL_OPS]. */
    private fun emitDecimalBinary(expr: BinaryExpr): String {
        val l = emitAsDecimal(expr.left)
        val r = emitAsDecimal(expr.right)
        val mc = "dev.kobol.stdlib.KobolMathContext.current()"
        return when (expr.op) {
            BinaryOp.EQ       -> "($l.compareTo($r) == 0)"
            BinaryOp.NEQ      -> "($l.compareTo($r) != 0)"
            BinaryOp.LT       -> "($l.compareTo($r) < 0)"
            BinaryOp.GT       -> "($l.compareTo($r) > 0)"
            BinaryOp.LEQ      -> "($l.compareTo($r) <= 0)"
            BinaryOp.GEQ      -> "($l.compareTo($r) >= 0)"
            BinaryOp.ADD      -> "($mc != null ? $l.add($r, $mc) : $l.add($r))"
            BinaryOp.SUBTRACT -> "($mc != null ? $l.subtract($r, $mc) : $l.subtract($r))"
            BinaryOp.MULTIPLY -> "($mc != null ? $l.multiply($r, $mc) : $l.multiply($r))"
            BinaryOp.DIVIDE   ->
                if (expr.dividingMode != null) "$l.divide($r, java.math.RoundingMode.${expr.dividingMode.replace('-', '_')})"
                else "($mc != null ? $l.divide($r, $mc) : $l.divide($r, java.math.RoundingMode.HALF_EVEN))"
            // BigDecimal.pow takes an int exponent; emit the raw (long) exponent cast to int.
            BinaryOp.POWER    -> "$l.pow((int)(${emitExpr(expr.right)}))"
            else -> error("emitDecimalBinary: ${expr.op} not a decimal op")
        }
    }

    /** True when [expr]'s static type is a fixed-point decimal (DECIMAL or MONEY). */
    private fun isDecimalExpr(expr: Expression): Boolean {
        // A DECIMAL literal already emits as `new BigDecimal(...)`; the checker does
        // not always tag bare literals, so recognise the literal kind directly.
        if (expr is Literal && expr.kind == LiteralKind.DECIMAL) return true
        return when (checker.typeOf(expr)) {
            is KobolType.DecimalType, is KobolType.MoneyType -> true
            else -> false
        }
    }

    /**
     * Emit [expr] as a BigDecimal. Decimal-typed exprs pass through; a primitive
     * operand in a mixed expression (e.g. `balance > 0`) is widened via
     * `BigDecimal.valueOf(...)` so `.compareTo`/`.add` type-check.
     */
    private fun emitAsDecimal(expr: Expression): String {
        val code = emitExpr(expr)
        return if (isDecimalExpr(expr)) code else "java.math.BigDecimal.valueOf($code)"
    }

    /**
     * Emit [expr] for assignment to a slot of type [target]. When the slot is a
     * decimal but the value is a primitive numeric (e.g. `total : DECIMAL = 0`),
     * widen to BigDecimal so the generated Java type-checks — otherwise pass through.
     */
    private fun emitExprFor(target: KobolType, expr: Expression): String =
        if ((target is KobolType.DecimalType || target is KobolType.MoneyType) && !isDecimalExpr(expr))
            emitAsDecimal(expr)
        else
            emitExpr(expr)

    /**
     * Render procedure-call arguments coerced to each declared parameter type — the Java twin of
     * AsmEmitter.emitProcArgs (G10). An INTEGER (`long`) argument into a DECIMAL/MONEY parameter is
     * widened to BigDecimal (else javac rejects `long`→BigDecimal); into a SMALLINT (`int`) slot it
     * is narrowed with `(int)`. `params` is null when the procedure can't be resolved (defensive) —
     * fall back to a bare emit, exactly as before. Same per-arg coercion as the ASM backend (P1).
     */
    private fun emitProcArgs(args: List<Expression>, params: List<Symbol.ProcedureSymbol.Param>?): String =
        args.mapIndexed { i, arg ->
            when (val p = params?.getOrNull(i)?.type) {
                is KobolType.DecimalType, is KobolType.MoneyType -> emitExprFor(p, arg)
                is KobolType.SmallIntType ->
                    if (checker.typeOf(arg) is KobolType.IntegerType) "(int)(${emitExpr(arg)})" else emitExpr(arg)
                else -> emitExpr(arg)
            }
        }.joinToString(", ")

    /**
     * Full static type of a reference, walking any field chain — so a record-field
     * target like `invoice.amount` resolves to the field's DECIMAL type, not the
     * record's. O(depth) in the number of `.`-separated parts.
     */
    private fun refType(ref: Reference): KobolType = checker.typeOfReference(ref)

    private fun emitStringTemplate(expr: StringTemplateExpr): String {
        if (expr.parts.isEmpty()) return "\"\""
        return expr.parts.joinToString(" + ") { part ->
            when (part) {
                is StringTemplatePart.RawText      -> "\"${escapeJavaString(part.text)}\""
                is StringTemplatePart.Interpolated -> "(${emitExpr(part.expr)})"
            }
        }
    }

    private fun emitBuiltin(expr: BuiltinCall): String {
        val args = expr.args.map { emitExpr(it) }
        return when (expr.name.uppercase()) {
            "COMBINE"   -> "KobolText.combine(${args.joinToString(", ")})"
            "UPPERCASE" -> "KobolText.uppercase(${args[0]})"
            "LOWERCASE" -> "KobolText.lowercase(${args[0]})"
            "TRIM"      -> "KobolText.trim(${args[0]})"
            "LENGTH"    -> "(long)KobolText.length(${args[0]})"
            "FIND"      -> "(long)KobolText.find(${args[0]}, ${args[1]})"
            "SUBSTRING" -> "KobolText.substring(${args[0]}, (int)${args[1]}, (int)${args[2]})"
            "REPLACE"   -> "KobolText.replace(${args[0]}, ${args[1]}, ${args[2]})"
            "REVERSE"   -> "KobolText.reverse(${args[0]})"
            "SPLIT"     -> when (args.size) {
                3    -> "KobolText.split(${args[0]}, ${args[1]}, (long)${args[2]})"
                else -> "KobolText.split(${args[0]}, ${args[1]})"
            }
            "ABS"       -> "KobolDecimal.abs(${args[0]})"
            "ROUND"     -> when (args.size) {
                3    -> "KobolDecimal.roundWithMode(${args[0]}, (int)${args[1]}, ${args[2]})"
                else -> "KobolDecimal.round(${args[0]}, (int)${args[1]})"
            }
            "ROUND-WITH-MODE" -> "KobolDecimal.roundWithMode(${args[0]}, (int)${args[1]}, ${args[2]})"
            "IS-BLANK"        -> "KobolText.isBlank(${args[0]})"
            "CONFIRM"         -> "dev.kobol.runtime.KobolEnv.confirm(${args[0]})"
            "IS-EMPTY"        -> "${args[0]}.isEmpty()"
            "IS-POSITIVE"     -> "dev.kobol.stdlib.KobolMath.isPositive(${args[0]})"
            "IS-NEGATIVE"     -> "dev.kobol.stdlib.KobolMath.isNegative(${args[0]})"
            "IS-ZERO"         -> "dev.kobol.stdlib.KobolMath.isZero(${args[0]})"
            "SCALE-OF"        -> "dev.kobol.stdlib.KobolMath.scaleOf(${args[0]})"
            "PRECISION-OF"    -> "dev.kobol.stdlib.KobolMath.precisionOf(${args[0]})"
            "UUID-GENERATE"   -> "dev.kobol.stdlib.KobolUuid.generate()"
            "UUID-NIL"        -> "dev.kobol.stdlib.KobolUuid.nil()"
            "UUID-FROM-TEXT"  -> "dev.kobol.stdlib.KobolUuid.fromText(${args[0]})"
            "UUID-TO-TEXT"    -> "dev.kobol.stdlib.KobolUuid.toText(${args[0]})"
            "TRUNCATE"        -> "KobolDecimal.truncate(${args[0]}, (int)${args[1]})"
            "MAX"       -> "KobolDecimal.max(${args[0]}, ${args[1]})"
            "MIN"       -> "KobolDecimal.min(${args[0]}, ${args[1]})"
            "DISPLAY_TABLE"       -> "KobolDisplay.table(${args[0]})"
            "DISPLAY_LABEL"       -> "KobolDisplay.label(${args[0]}, ${args[1]})"
            "DISPLAY_FORMAT"      -> "KobolDisplay.format(${args[0]}, ${args[1]})"
            "DISPLAY_JSON"        -> "dev.kobol.stdlib.KobolJson.toJson(${args[0]})"
            "DISPLAY_JSON_PRETTY" -> "dev.kobol.stdlib.KobolJson.toPrettyJson(${args[0]})"
            "DISPLAY_STYLED"      -> "dev.kobol.runtime.KobolDisplay.styled(${args[0]}, ${args[1]}, ${args[2]}, ${args[3]})"
            "DISPLAY_XML"         -> "dev.kobol.stdlib.KobolXml.toXml(${args[0]})"
            "DISPLAY_XML_PRETTY"  -> "dev.kobol.stdlib.KobolXml.toPrettyXml(${args[0]})"
            // User-defined procedure called in expression position (e.g. COMPUTE x = Fee(5)) — coerce
            // each arg to the declared param type so an INTEGER literal into a DECIMAL param widens
            // to BigDecimal, mirroring the PERFORM path (G10). Unresolved → bare emit, as before.
            else -> {
                val sym = checker.symbols.resolve(expr.name) as? Symbol.ProcedureSymbol
                "${expr.name}(${emitProcArgs(expr.args, sym?.params)})"
            }
        }
    }

    private fun emitPipeline(expr: PipelineExpr): String {
        // Emit as Java stream operations
        var chain = "${emitExpr(expr.source)}.stream()"
        for (stage in expr.stages) {
            chain += when (stage) {
                is PipelineStage.FilterStage    -> ".filter(__item -> ${emitExpr(stage.condition)})"
                is PipelineStage.TransformStage -> ".map(__item -> __item.${javaIdent(stage.field)})"
                is PipelineStage.SumStage       -> ".map(x -> x instanceof java.math.BigDecimal ? (java.math.BigDecimal)x : java.math.BigDecimal.valueOf(((Number)x).longValue())).reduce(java.math.BigDecimal.ZERO, java.math.BigDecimal::add)"
                is PipelineStage.SortStage      ->
                    if (stage.descending) ".sorted(java.util.Comparator.comparing(__item -> __item.${javaIdent(stage.field)}, java.util.Comparator.reverseOrder()))"
                    else                 ".sorted(java.util.Comparator.comparing(__item -> __item.${javaIdent(stage.field)}))"
                is PipelineStage.TakeStage      -> ".limit((long)(${emitExpr(stage.count)}))"
            }
        }
        // Terminate based on last stage
        val lastStage = expr.stages.lastOrNull()
        if (lastStage !is PipelineStage.SumStage) chain += ".collect(java.util.stream.Collectors.toList())"
        return chain
    }

    /** §27.1 ACCEPT — read raw String (terminal/argument), coerce to the target type, assign. */
    private fun emitAccept(stmt: AcceptStatement) {
        val name = stmt.target.parts.last()
        val raw = if (stmt.fromTerminal) {
            "dev.kobol.runtime.KobolEnv.acceptTerminal(${emitExpr(stmt.source)})"
        } else {
            val def = stmt.default?.let { "String.valueOf(${emitExpr(it)})" } ?: "\"\""
            "dev.kobol.runtime.KobolEnv.acceptArgument(${emitExpr(stmt.source)}, $def)"
        }
        val env = "dev.kobol.runtime.KobolEnv"
        val coerced = when (refType(stmt.target)) {
            is KobolType.IntegerType                         -> "$env.toLong($raw, \"$name\")"
            is KobolType.DecimalType, is KobolType.MoneyType -> "$env.toDecimal($raw, \"$name\")"
            is KobolType.BooleanType                         -> "$env.toBoolean($raw, \"$name\")"
            is KobolType.DateType                            -> "$env.toDate($raw, \"$name\")"
            is KobolType.TimeType                            -> "$env.toTime($raw, \"$name\")"
            is KobolType.DateTimeType                        -> "$env.toDateTime($raw, \"$name\")"
            else                                             -> raw   // TEXT / unknown
        }
        line("${emitRef(stmt.target)} = $coerced;")
    }

    private fun emitRef(ref: Reference): String {
        if (ref.parts.size == 1) {
            val namedCond = namedConditions[ref.parts[0]]
            if (namedCond != null) return "(${emitExpr(namedCond)})"
        }
        return ref.parts.joinToString(".") { javaIdent(it) }
    }

    // -------------------------------------------------------------------------
    // Helpers
    // -------------------------------------------------------------------------

    private fun line(s: String) {
        sb.append("    ".repeat(indent)).appendLine(s)
    }

    private fun blank() { sb.appendLine() }

    private val javaClassCache = HashMap<String, String>()

    private fun javaClass(kobolName: String): String {
        // CUSTOMER-REPORT → CustomerReport
        return javaClassCache.getOrPut(kobolName) {
            kobolName.split("-").joinToString("") { it.lowercase().replaceFirstChar { c -> c.uppercase() } }
        }
    }

    private val javaIdentCache = HashMap<String, String>()

    private fun javaIdent(kobolName: String): String =
        javaIdentCache.getOrPut(kobolName) {
            // CUSTOMER-NAME → customerName  (camelCase)
            val parts = kobolName.lowercase().split("-")
            parts[0] + parts.drop(1).joinToString("") { it.replaceFirstChar { c -> c.uppercase() } }
        }

    private fun f(name: String) = javaIdent(name)

    private fun kobolTypeToJava(type: KobolType): String = when (type) {
        is KobolType.IntegerType   -> "long"
        is KobolType.SmallIntType  -> "int"
        is KobolType.BooleanType   -> "boolean"
        is KobolType.DateType      -> "LocalDate"
        is KobolType.TimeType      -> "LocalTime"
        is KobolType.DateTimeType  -> "LocalDateTime"
        is KobolType.DecimalType   -> "BigDecimal"
        is KobolType.MoneyType     -> "BigDecimal"
        is KobolType.TextType      -> "String"
        is KobolType.ListType      -> "List<${kobolTypeToJava(type.elementType)}>"
        is KobolType.MapType       -> "Map<${kobolTypeToJava(type.keyType)}, ${kobolTypeToJava(type.valueType)}>"
        is KobolType.FutureType    -> "java.util.concurrent.CompletableFuture<${kobolTypeToJava(type.elementType)}>"
        is KobolType.RecordRefType  -> javaClass(type.name)
        is KobolType.VariantRefType  -> javaClass(type.name)
        is KobolType.JavaObjectType  -> "Object"
        is KobolType.VoidType        -> "void"
        is KobolType.UnknownType     -> "Object"
        is KobolType.UuidType        -> "java.util.UUID"
    }

    private fun defaultValue(type: KobolType): String = when (type) {
        is KobolType.IntegerType   -> "0L"
        is KobolType.SmallIntType  -> "0"
        is KobolType.BooleanType   -> "false"
        is KobolType.DecimalType,
        is KobolType.MoneyType     -> "BigDecimal.ZERO"
        is KobolType.TextType      -> "\"\""
        is KobolType.DateType      -> "LocalDate.now()"
        is KobolType.TimeType      -> "LocalTime.now()"
        is KobolType.DateTimeType  -> "LocalDateTime.now()"
        is KobolType.ListType      -> "new ArrayList<>()"
        is KobolType.MapType       -> "new LinkedHashMap<>()"
        is KobolType.RecordRefType -> "new ${javaClass(type.name)}()"
        else                       -> "null"
    }

    private fun escapeJavaString(s: String): String =
        s.replace("\\", "\\\\").replace("\"", "\\\"").replace("\n", "\\n").replace("\r", "\\r")

    private fun inferLiteralType(expr: Expression): KobolType = when (expr) {
        is Literal -> when (expr.kind) {
            LiteralKind.INTEGER -> KobolType.IntegerType
            LiteralKind.DECIMAL -> KobolType.DecimalType(10, 2)
            LiteralKind.STRING  -> KobolType.TextType(null)
            LiteralKind.BOOLEAN -> KobolType.BooleanType
        }
        is StringTemplateExpr -> KobolType.TextType(null)
        else -> checker.typeOf(expr).takeIf { it != KobolType.UnknownType } ?: KobolType.TextType(null)
    }

    companion object {
        private val MONGO_COMPARISON_OPS = setOf(
            BinaryOp.EQ, BinaryOp.NEQ, BinaryOp.LT, BinaryOp.GT, BinaryOp.LEQ, BinaryOp.GEQ
        )

        /** Binary ops that need BigDecimal-method emission when operands are decimal. */
        private val DECIMAL_OPS = setOf(
            BinaryOp.EQ, BinaryOp.NEQ, BinaryOp.LT, BinaryOp.GT, BinaryOp.LEQ, BinaryOp.GEQ,
            BinaryOp.ADD, BinaryOp.SUBTRACT, BinaryOp.MULTIPLY, BinaryOp.DIVIDE, BinaryOp.POWER
        )
    }
}
